question_data =[
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"medium",
    "question":"All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
    "correct_answer":"False",
    "incorrect_answers":["True"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"easy",
    "question":"Linus Torvalds created Linux and Git.",
    "correct_answer":"True",
    "incorrect_answers":["False"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"easy",
    "question":"The logo for Snapchat is a Bell.",
    "correct_answer":"False",
    "incorrect_answers":["True"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"easy",
    "question":"Ada Lovelace is often considered the first computer programmer.",
    "correct_answer":"True","incorrect_answers":["False"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"medium",
    "question":"MacOS is based on Linux.",
    "correct_answer":"False",
    "incorrect_answers":["True"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"easy",
    "question":"In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
    "correct_answer":"True",
    "incorrect_answers":["False"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"easy",
    "question":"The Windows ME operating system was released in the year 2000.",
    "correct_answer":"True",
    "incorrect_answers":["False"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"medium",
    "question":"It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
    "correct_answer":"True",
    "incorrect_answers":["False"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"easy",
    "question":"Linux was first created as an alternative to Windows XP.",
    "correct_answer":"False",
    "incorrect_answers":["True"],
    },
    {
    "category":"Science: Computers",
    "type":"boolean",
    "difficulty":"medium",
    "question":"Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
    "correct_answer":"False",
    "incorrect_answers":["True"],
    },
    ]